/**
 * Seeded corpus.
 *
 * Stands in for stages 1-4 of the pipeline (Apify ingest, baseline detection,
 * Gemini extraction, Claude reasoning). The shapes here are exactly what those
 * stages are specified to produce in ../../PLAN.md §4, so swapping in the real
 * adapter is a data-source change, not a rewrite.
 *
 * Deliberately includes posts that get rejected, filtered and gated, so the
 * funnel is visible rather than implied.
 */

/* ------------------------------------------------------------------ *
 * Clients
 * ------------------------------------------------------------------ */

export const CLIENTS = [
  {
    id: 'bosporus',
    name: 'Bosporus Grill',
    cuisine: 'Kebab / Turkish grill',
    city: 'Dresden',
    site: 'Food court, Centrum Galerie',
    accent: 198,
    brief:
      'Fun and jokes. High footfall, very low dwell time. Everything shot behind or in front of a 4-metre counter — there is no back room and no outdoor space.',
    capability: {
      spaces: ['counter', 'small_kitchen', 'shared_seating'],
      chefOnCamera: 'high',
      customersOnCamera: true,
      staffCount: 4,
      staffAvailableForFilming: 2,
      staffMinutesPerConcept: 45,
      monthlyBudgetEur: 150,
      ownBaselineViews: 2400,
      equipment: ['phone', 'tripod'],
      preferredTones: {
        comedy: 1.0,
        challenge: 0.9,
        energetic: 0.85,
        satisfying: 0.7,
        transformation: 0.6,
        heartwarming: 0.5,
        educational: 0.4,
        craft: 0.35,
        story: 0.3,
        shock: 0.45,
      },
      avoidTones: ['luxury'],
      constraints: [
        'No outdoor area — mall interior only',
        'Seating is shared food-court seating, not ours',
        'Mall filming rules: no tripods in walkways during opening hours',
      ],
    },
  },
  {
    id: 'sen',
    name: 'Sen Vietnamese',
    cuisine: 'Vietnamese',
    city: 'Dresden',
    site: 'Sit-down restaurant, Neustadt',
    accent: 152,
    brief:
      'Craft and warmth over jokes. Full kitchen, own dining room, small terrace. Guests must not be identifiable on camera without written consent.',
    capability: {
      spaces: ['counter', 'small_kitchen', 'full_kitchen', 'dining_room', 'outdoor'],
      chefOnCamera: 'medium',
      customersOnCamera: false,
      staffCount: 8,
      staffAvailableForFilming: 3,
      staffMinutesPerConcept: 90,
      monthlyBudgetEur: 300,
      ownBaselineViews: 3100,
      equipment: ['phone', 'tripod', 'light', 'gimbal'],
      preferredTones: {
        craft: 1.0,
        story: 0.95,
        heartwarming: 0.9,
        satisfying: 0.85,
        educational: 0.7,
        transformation: 0.6,
        energetic: 0.4,
        comedy: 0.3,
        challenge: 0.25,
        luxury: 0.5,
      },
      avoidTones: ['shock'],
      constraints: [
        'No identifiable guests without written consent',
        'Kitchen is only free between 15:00 and 17:00',
      ],
    },
  },
  {
    id: 'nonna',
    name: 'Trattoria da Nonna',
    cuisine: 'Italian family trattoria',
    city: 'Leipzig',
    site: 'Sit-down restaurant',
    accent: 22,
    brief:
      'Family warmth, generational story, visible craft. Chef is camera-shy; the owner’s mother is not.',
    capability: {
      spaces: ['counter', 'small_kitchen', 'full_kitchen', 'dining_room'],
      chefOnCamera: 'low',
      customersOnCamera: true,
      staffCount: 6,
      staffAvailableForFilming: 2,
      staffMinutesPerConcept: 60,
      monthlyBudgetEur: 200,
      ownBaselineViews: 1900,
      equipment: ['phone', 'tripod', 'light'],
      preferredTones: {
        heartwarming: 1.0,
        craft: 0.85,
        story: 0.8,
        satisfying: 0.75,
        transformation: 0.7,
        educational: 0.6,
        comedy: 0.5,
        energetic: 0.4,
        challenge: 0.3,
        shock: 0.2,
      },
      avoidTones: [],
      constraints: ['Head chef will not appear on camera', 'No filming Fri/Sat service'],
    },
  },
];

/* ------------------------------------------------------------------ *
 * Creators + synthetic history (drives the real baseline computation)
 * ------------------------------------------------------------------ */

const CREATOR_SEEDS = [
  ['c1', 'kebab_king_berlin', 'Kebab / street food', 22000],
  ['c2', 'dresden_streetfood', 'Street food', 14500],
  ['c3', 'pho_hanoi_official', 'Vietnamese', 31000],
  ['c4', 'chefmarco_pasta', 'Italian', 46000],
  ['c5', 'the_kitchen_diary', 'Restaurant life', 9800],
  ['c6', 'mallfood_tokyo', 'Food court', 62000],
  ['c7', 'saigon_kitchen_uk', 'Vietnamese', 18700],
  ['c8', 'grill_bros', 'Grill / kebab', 27400],
  ['c9', 'tiny_kitchen_vienna', 'Small-space cooking', 7300],
  ['c10', 'restaurant_reels_de', 'Restaurant marketing', 12100],
  ['c11', 'michelin_moments', 'Fine dining', 88000],
  ['c12', 'family_trattoria', 'Italian family', 15600],
];

/** Deterministic PRNG so baselines never move between reloads. */
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

export const CREATORS = CREATOR_SEEDS.map(([id, handle, niche, baselineViews], i) => {
  const rand = rng(1000 + i * 77);
  const history = Array.from({ length: 14 }, (_, j) => ({
    id: `${id}-h${j}`,
    mediaType: 'reel',
    // 0.55x - 1.5x around the baseline, plus one deliberate prior spike so the
    // median-not-mean choice actually matters.
    views: Math.round(baselineViews * (j === 4 ? 6.2 : 0.55 + rand() * 0.95)),
    ageDays: 16 + j * 6,
  }));
  return { id, handle, niche, baselineViews, history };
});

/* ------------------------------------------------------------------ *
 * Posts + extracted attributes + reasoning
 * ------------------------------------------------------------------ */

const P = (o) => o;

export const POSTS = [
  P({
    id: 'p1',
    creatorId: 'c1',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p1',
    views: 780000,
    likes: 61200,
    comments: 2140,
    ageDays: 34,
    durationS: 27,
    caption: 'He said €10. I said say less. 😤 #kebab #streetfood',
    poster: { hue: 24, glyph: '🔥' },
    videoUrl: null,
    attributes: {
      hookType: 'curiosity',
      format: 'customer_interaction',
      tone: 'challenge',
      secondaryTone: 'comedy',
      peopleOnCamera: 2,
      chefOnCamera: true,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 12,
      staffMinutes: 35,
      cuts: 9,
      avgShotLengthS: 3.0,
    },
    transcript:
      '"Ten euro. Make me whatever you want." — "Whatever I want?" — "Whatever you want." … "Bro. That is not ten euros of food."',
    timeline: [
      { t: 0, label: 'Customer slides a €10 note across the counter' },
      { t: 3, label: 'Chef pauses, looks at camera' },
      { t: 6, label: 'Fast build sequence, no dialogue' },
      { t: 19, label: 'Reveal — plate is visibly oversized' },
      { t: 23, label: 'Customer reaction, genuine laugh' },
    ],
    mechanism:
      'Handing creative control to the maker converts a transaction into a bet. The viewer stays to find out whether the chef over- or under-delivers; the reveal resolves a wager the viewer placed for free.',
    essentialElements: [
      'Customer surrenders the decision, on camera',
      'A visible constraint (the price) the audience can judge against',
      'An unambiguous reveal that beats expectation',
      'A real, unperformed reaction',
    ],
    incidentalElements: ['The €10 figure', 'Kebab specifically', 'The chef’s personality'],
    adaptations: {
      bosporus:
        'Run it as "€8 and I trust you" at the counter, filmed from the customer side so the mall background is out of focus. The reveal has to be physically bigger than a normal order — stack it so the size difference reads in one frame. Two staff, one lunch shift, no props beyond the food itself.',
      sen:
        'Reframe from bet to trust: "Chef, cook me what you would eat." Guest is off-camera and unidentifiable; the entire piece is the chef’s hands and the plate. Loses the comedy, keeps the reveal, fits the no-guests rule.',
      nonna:
        'Give the decision to Nonna rather than the chef — "€10, and Nonna decides." The generational twist replaces the comedy beat and gets your camera-shy chef out of it entirely.',
    },
  }),

  P({
    id: 'p2',
    creatorId: 'c8',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p2',
    views: 512000,
    likes: 44800,
    comments: 903,
    ageDays: 41,
    durationS: 18,
    caption: 'the shave. every time. 🌀',
    poster: { hue: 38, glyph: '🌀' },
    videoUrl: null,
    attributes: {
      hookType: 'visual_spectacle',
      format: 'b_roll',
      tone: 'satisfying',
      secondaryTone: 'craft',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 20,
      cuts: 4,
      avgShotLengthS: 4.5,
    },
    transcript: '[no speech — blade, meat, and the sound of the cone turning]',
    timeline: [
      { t: 0, label: 'Extreme close-up, blade enters frame' },
      { t: 2, label: 'First shave falls in slow motion' },
      { t: 8, label: 'Pull back to reveal full cone' },
      { t: 14, label: 'Pile lands on the board' },
    ],
    mechanism:
      'Uninterrupted competence at close range. No narrative, no payoff — the sensory loop is the product, which is why it retains without a hook line.',
    essentialElements: [
      'One repeated motion filmed closer than the eye normally gets',
      'Diegetic sound carrying the whole track',
      'No cuts that break the motion',
    ],
    incidentalElements: ['The specific dish', 'Slow motion as a technique'],
    adaptations: {
      bosporus:
        'You already own this shot — it is your daily work at 15cm instead of 2m. Phone on a tripod at counter height, mic pointed at the cone, one 20-second take between rushes. Cheapest concept on this list and the most repeatable.',
      sen:
        'Substitute the cone for the pho ladle: broth lifted and poured back, filmed from directly above at close range. Same sensory loop, no guests, no dialogue.',
      nonna:
        'Hand-cut pasta falling onto the board, close and slow. Chef never shows a face — only hands, which solves your camera-shy problem.',
    },
  }),

  P({
    id: 'p3',
    creatorId: 'c2',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p3',
    views: 268000,
    likes: 19400,
    comments: 1580,
    ageDays: 22,
    durationS: 34,
    caption: 'guess the price, eat for free 👀',
    poster: { hue: 280, glyph: '💸' },
    videoUrl: null,
    attributes: {
      hookType: 'curiosity',
      format: 'customer_reaction',
      tone: 'comedy',
      secondaryTone: 'challenge',
      peopleOnCamera: 3,
      chefOnCamera: false,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 8,
      staffMinutes: 50,
      cuts: 16,
      avgShotLengthS: 2.1,
    },
    transcript: '"If you guess the price within fifty cents, it is free." — "…six euro?" — "…"',
    timeline: [
      { t: 0, label: 'Rules stated to camera in one line' },
      { t: 4, label: 'First customer guesses, misses' },
      { t: 13, label: 'Second customer, closer' },
      { t: 24, label: 'Third guesses exactly, reaction' },
    ],
    mechanism:
      'The viewer plays along silently and is scored against strangers. Participation happens in the viewer’s head before the reveal, which is what holds them to the end.',
    essentialElements: [
      'A guessable quantity stated up front',
      'Multiple attempts to build a scale',
      'A win that actually costs the business something',
    ],
    incidentalElements: ['Price as the quantity', 'Free meal as the prize'],
    adaptations: {
      bosporus:
        'Perfect counter format — the queue is the cast. Run it as "guess the weight of your döner". Costs you a handful of free meals per shoot and needs no space beyond where you already stand. Budget 50 minutes across one lunch rush.',
      nonna:
        'Guess how many years the recipe has been in the family, rather than a price. Keeps the guessing loop, swaps the comedy for the heritage angle your audience responds to.',
    },
  }),

  P({
    id: 'p4',
    creatorId: 'c3',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p4',
    views: 690000,
    likes: 58300,
    comments: 1210,
    ageDays: 51,
    durationS: 44,
    caption: '12 hours. one shot every hour. 🍜',
    poster: { hue: 168, glyph: '🍜' },
    videoUrl: null,
    attributes: {
      hookType: 'transformation',
      format: 'food_preparation',
      tone: 'craft',
      secondaryTone: 'story',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'full_kitchen',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 70,
      cuts: 12,
      avgShotLengthS: 3.6,
    },
    transcript: '"Hour one. Hour four — you can see the colour changing. Hour twelve. This is it."',
    timeline: [
      { t: 0, label: 'Locked-off shot, clear water, bones going in' },
      { t: 9, label: 'Timestamp cards begin' },
      { t: 26, label: 'Colour shift becomes obvious' },
      { t: 38, label: 'Final strain and pour' },
    ],
    mechanism:
      'Time-compression makes invisible labour visible. The value proposition of the restaurant is argued without a single sales line — the viewer concludes it themselves.',
    essentialElements: [
      'A fixed camera position across the whole duration',
      'Explicit time markers so the effort is legible',
      'A visible state change between first and last frame',
    ],
    incidentalElements: ['12 hours specifically', 'Broth as the subject'],
    adaptations: {
      sen:
        'This is close to a native format for you — one locked-off tripod in the corner of the kitchen during a normal broth day, one shot per hour, no extra labour beyond pressing record. Fits the 15:00–17:00 window because the camera works while you do.',
      nonna:
        'Apply it to a 48-hour ragù or a dough prove. Same fixed frame, same timestamp cards; the chef is never in shot so the camera-shy constraint is irrelevant.',
    },
  }),

  P({
    id: 'p5',
    creatorId: 'c7',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p5',
    views: 903000,
    likes: 112000,
    comments: 4310,
    ageDays: 63,
    durationS: 52,
    caption: 'she has made it the same way since 1974.',
    poster: { hue: 340, glyph: '🕯️' },
    videoUrl: null,
    attributes: {
      hookType: 'story',
      format: 'interview',
      tone: 'story',
      secondaryTone: 'heartwarming',
      peopleOnCamera: 2,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_dining_room',
      spaceRequired: 'dining_room',
      equipment: ['phone', 'tripod', 'light'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 15,
      staffMinutes: 90,
      cuts: 11,
      avgShotLengthS: 4.7,
    },
    transcript:
      '"My mother wrote it down once and then threw the paper away. She said if you need to read it, you are not ready to cook it."',
    timeline: [
      { t: 0, label: 'Hands, not face — pastry being folded' },
      { t: 6, label: 'First line of voiceover lands' },
      { t: 21, label: 'Cut to her face for the first time' },
      { t: 44, label: 'Finished dish placed on a worn table' },
    ],
    mechanism:
      'A single specific detail — the discarded paper — does the work a generic heritage claim cannot. Specificity is the mechanism; the emotion is a consequence of it.',
    essentialElements: [
      'One concrete, checkable detail rather than a general claim',
      'Delaying the face until the voice has earned it',
      'Hands and texture carrying the first third',
    ],
    incidentalElements: ['1974', 'The grandmother relationship specifically'],
    adaptations: {
      sen:
        'Your strongest fit on this list. Find the one detail — the pot that came over, the herb that has to be bought from one supplier — and build 50 seconds around it. Needs the dining room after service and about 90 minutes with someone who can tell it plainly.',
      nonna:
        'Nonna is the asset here, not the chef. One detail, one telling, shot at a corner table before opening. This is the concept most likely to outperform your baseline.',
      bosporus:
        'Harder for you — no dining room and a food-court background that fights the mood. If you want it, shoot tight against the counter tile at close range and treat it as a 25-second version.',
    },
  }),

  P({
    id: 'p6',
    creatorId: 'c10',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p6',
    views: 340000,
    likes: 26100,
    comments: 2890,
    ageDays: 29,
    durationS: 41,
    caption: 'I reviewed my own restaurant as a mystery customer 💀',
    poster: { hue: 258, glyph: '🕵️' },
    videoUrl: null,
    attributes: {
      hookType: 'controversy',
      format: 'pov',
      tone: 'comedy',
      secondaryTone: 'story',
      peopleOnCamera: 2,
      chefOnCamera: true,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'any_dining_room',
      spaceRequired: 'dining_room',
      equipment: ['phone'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 20,
      staffMinutes: 55,
      cuts: 18,
      avgShotLengthS: 2.3,
    },
    transcript: '"Service: seven out of ten. Portion size — we need to talk about the portion size."',
    timeline: [
      { t: 0, label: 'Owner sits down at own restaurant, disguised badly' },
      { t: 5, label: 'Scores announced as captions' },
      { t: 22, label: 'A genuinely critical score appears' },
      { t: 34, label: 'Staff realise mid-service' },
    ],
    mechanism:
      'Voluntary self-criticism buys credibility that praise cannot. The audience trusts the positive scores precisely because a negative one appeared.',
    essentialElements: [
      'At least one real criticism the business will act on',
      'The owner exposed rather than protected',
      'Scores stated concretely, not vaguely',
    ],
    incidentalElements: ['The disguise gag', 'Review format specifically'],
    adaptations: {
      bosporus:
        'Do it standing in your own queue at peak. The mall setting works for once — you are genuinely one of many counters, so the "would I pick us?" framing is real. Must include one criticism you then visibly fix in a follow-up.',
      nonna:
        'Have a family member review, not the owner — softer register, same credibility mechanism, and it keeps your chef off camera.',
    },
  }),

  P({
    id: 'p7',
    creatorId: 'c6',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p7',
    views: 1240000,
    likes: 98700,
    comments: 3120,
    ageDays: 37,
    durationS: 22,
    caption: 'food court, 12:30, POV 🏃',
    poster: { hue: 8, glyph: '⚡' },
    videoUrl: null,
    attributes: {
      hookType: 'visual_spectacle',
      format: 'pov',
      tone: 'energetic',
      secondaryTone: 'satisfying',
      peopleOnCamera: 2,
      chefOnCamera: false,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone', 'gimbal'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'trending_sound',
      trendHalfLifeDays: 21,
      propsCostEur: 0,
      staffMinutes: 25,
      cuts: 21,
      avgShotLengthS: 1.0,
    },
    transcript: '[no speech — trending audio over service sounds]',
    timeline: [
      { t: 0, label: 'Camera moves into the pass at speed' },
      { t: 4, label: 'Rapid cuts on the beat' },
      { t: 12, label: 'Order counter hand-off' },
      { t: 18, label: 'Freeze on the finished tray' },
    ],
    mechanism:
      'Speed as reassurance. A crowded, fast operation reads as social proof — the viewer infers quality from demand without being told.',
    essentialElements: [
      'Genuine peak-hour density (staged calm does not work)',
      'Cut rhythm locked to the audio',
      'A single continuous journey through the space',
    ],
    incidentalElements: ['The specific audio track', 'Gimbal movement'],
    adaptations: {
      bosporus:
        'Your queue at 12:30 is the entire asset and you have not used it. Handheld is fine — a gimbal is not required if you brace against the counter. Watch the 21-day trend window: shoot within a week of picking the audio.',
    },
  }),

  P({
    id: 'p8',
    creatorId: 'c5',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p8',
    views: 187000,
    likes: 21300,
    comments: 1940,
    ageDays: 26,
    durationS: 31,
    caption: 'reading our worst review out loud 🙃',
    poster: { hue: 218, glyph: '📝' },
    videoUrl: null,
    attributes: {
      hookType: 'controversy',
      format: 'talking_head',
      tone: 'comedy',
      secondaryTone: 'heartwarming',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'small_kitchen',
      equipment: ['phone'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 25,
      cuts: 6,
      avgShotLengthS: 5.2,
    },
    transcript: '"One star. \'The chef looked at me.\' … I did. I do that. I look at people."',
    timeline: [
      { t: 0, label: 'Phone held up, review read cold' },
      { t: 7, label: 'Beat of genuine silence' },
      { t: 12, label: 'Deadpan response' },
      { t: 25, label: 'Returns to work mid-sentence' },
    ],
    mechanism:
      'Absorbing an attack without defending converts hostility into likeability. The restraint is the joke; a rebuttal would kill it.',
    essentialElements: [
      'A real review, read verbatim',
      'No defensive explanation',
      'A dry rather than triumphant response',
    ],
    incidentalElements: ['One-star specifically', 'Kitchen setting'],
    adaptations: {
      bosporus:
        'Cheapest thing on the board: one person, one phone, 25 minutes, no props. Read a genuine bad review at the counter between rushes. The rule is no defending — the moment you explain yourself it stops working.',
      nonna:
        'Have Nonna read it rather than the chef. Same mechanism, warmer register, and it dodges the camera-shy constraint entirely.',
    },
  }),

  P({
    id: 'p9',
    creatorId: 'c11',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p9',
    views: 4100000,
    likes: 402000,
    comments: 11200,
    ageDays: 44,
    durationS: 29,
    caption: 'he walked in with no reservation.',
    poster: { hue: 48, glyph: '⭐' },
    videoUrl: null,
    attributes: {
      hookType: 'surprise',
      format: 'behind_the_scenes',
      tone: 'shock',
      secondaryTone: 'story',
      peopleOnCamera: 4,
      chefOnCamera: true,
      customersOnCamera: true,
      namedPersonDependency: true,
      locationType: 'any_dining_room',
      spaceRequired: 'dining_room',
      equipment: ['phone', 'second_camera'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 60,
      cuts: 19,
      avgShotLengthS: 1.5,
    },
    transcript: '"Table for one." — [kitchen erupts]',
    timeline: [
      { t: 0, label: 'Door opens, recognisable figure enters' },
      { t: 3, label: 'Staff double-take' },
      { t: 11, label: 'Kitchen scramble' },
      { t: 24, label: 'Plate delivered, reaction shot' },
    ],
    mechanism:
      'Borrowed status. The video performs because of who walked in, not because of anything the restaurant designed — which is exactly why it does not transfer.',
    essentialElements: ['A person the audience already recognises'],
    incidentalElements: ['Everything else in the video'],
    adaptations: {},
  }),

  P({
    id: 'p10',
    creatorId: 'c11',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p10',
    views: 1150000,
    likes: 94000,
    comments: 1640,
    ageDays: 55,
    durationS: 24,
    caption: 'sunset service, 14th floor.',
    poster: { hue: 302, glyph: '🚁' },
    videoUrl: null,
    attributes: {
      hookType: 'visual_spectacle',
      format: 'b_roll',
      tone: 'luxury',
      secondaryTone: 'craft',
      peopleOnCamera: 6,
      chefOnCamera: false,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'unique_venue',
      spaceRequired: 'outdoor',
      equipment: ['drone', 'gimbal', 'light'],
      editComplexity: 'vfx_motion_graphics',
      audioDependency: 'licensed_music',
      trendHalfLifeDays: null,
      propsCostEur: 200,
      staffMinutes: 120,
      cuts: 14,
      avgShotLengthS: 1.7,
    },
    transcript: '[no speech — licensed orchestral bed]',
    timeline: [
      { t: 0, label: 'Drone rises past the building edge' },
      { t: 7, label: 'Terrace revealed at golden hour' },
      { t: 15, label: 'Push in to a single table' },
      { t: 21, label: 'Logo sting' },
    ],
    mechanism:
      'Production value as the entire proposition. Nothing here is a transferable idea — it is a budget, filmed.',
    essentialElements: ['A rooftop', 'A drone operator', 'A licensing budget'],
    incidentalElements: ['The food'],
    adaptations: {},
  }),

  P({
    id: 'p11',
    creatorId: 'c9',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p11',
    views: 214000,
    likes: 24600,
    comments: 611,
    ageDays: 19,
    durationS: 12,
    caption: 'wait for it 🧀',
    poster: { hue: 44, glyph: '🧀' },
    videoUrl: null,
    attributes: {
      hookType: 'curiosity',
      format: 'b_roll',
      tone: 'satisfying',
      secondaryTone: 'transformation',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'small_kitchen',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 5,
      staffMinutes: 15,
      cuts: 3,
      avgShotLengthS: 4.0,
    },
    transcript: '[no speech]',
    timeline: [
      { t: 0, label: 'Knife enters, nothing visible yet' },
      { t: 4, label: 'First separation' },
      { t: 7, label: 'Full pull, held' },
    ],
    mechanism:
      'A promised payoff withheld for exactly long enough. Twelve seconds is the format — any longer and the tension leaks out.',
    essentialElements: [
      'An explicit promise in the first second',
      'One physical payoff, not a montage',
      'Ruthlessly short duration',
    ],
    incidentalElements: ['Cheese', 'Slow motion'],
    adaptations: {
      bosporus:
        'Sauce pour or the first cut into a fresh cone — anything with one held payoff. Fifteen minutes of staff time. Run this one weekly as filler between the bigger concepts.',
      sen:
        'Broth poured over noodles, filmed at the moment the steam rises. Same withheld-payoff structure, no dialogue, no guests.',
      nonna:
        'Burrata or a cut into a baked pasta. Hands only — no face required.',
    },
  }),

  P({
    id: 'p12',
    creatorId: 'c2',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p12',
    views: 402000,
    likes: 33900,
    comments: 2450,
    ageDays: 31,
    durationS: 38,
    caption: 'the weirdest order we have ever had 😭',
    poster: { hue: 92, glyph: '🤢' },
    videoUrl: null,
    attributes: {
      hookType: 'curiosity',
      format: 'challenge',
      tone: 'comedy',
      secondaryTone: 'challenge',
      peopleOnCamera: 3,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 10,
      staffMinutes: 45,
      cuts: 15,
      avgShotLengthS: 2.5,
    },
    transcript: '"Someone actually ordered this." — "No." — "Yes." — "…make it."',
    timeline: [
      { t: 0, label: 'Order ticket held to camera' },
      { t: 4, label: 'Staff reactions, unscripted' },
      { t: 14, label: 'Reluctant assembly' },
      { t: 30, label: 'Taste test, verdict' },
    ],
    mechanism:
      'Shared disgust is a bonding mechanism. The staff act as the audience’s proxy, so the viewer joins a group rather than watches one.',
    essentialElements: [
      'A genuinely real order, not invented',
      'Staff reacting honestly before they are told to',
      'A verdict at the end',
    ],
    incidentalElements: ['How weird the order actually is'],
    adaptations: {
      bosporus:
        'You have a ticket archive worth mining and staff who will react honestly. Three people, 45 minutes, one shoot yields two or three of these. Strongest recurring format for your tone.',
    },
  }),

  P({
    id: 'p13',
    creatorId: 'c7',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p13',
    views: 445000,
    likes: 39800,
    comments: 720,
    ageDays: 47,
    durationS: 58,
    caption: '300 spring rolls. one take. no cuts.',
    poster: { hue: 138, glyph: '🥢' },
    videoUrl: null,
    attributes: {
      hookType: 'authority',
      format: 'food_preparation',
      tone: 'craft',
      secondaryTone: 'satisfying',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'small_kitchen',
      equipment: ['phone', 'tripod'],
      editComplexity: 'single_take',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 25,
      staffMinutes: 80,
      cuts: 0,
      avgShotLengthS: 58,
    },
    transcript: '[no speech — paper, filling, the rhythm of folding]',
    timeline: [
      { t: 0, label: 'Caption states the claim, timer starts' },
      { t: 10, label: 'Rhythm established, hands only' },
      { t: 40, label: 'Tray filling visibly' },
      { t: 55, label: 'Last roll, timer stops' },
    ],
    mechanism:
      'The unbroken take is the proof. A cut would let the viewer suspect a shortcut, so the format itself is the credibility argument.',
    essentialElements: [
      'A verifiable claim stated up front',
      'No cuts — the constraint is the content',
      'Visible accumulation so progress reads',
    ],
    incidentalElements: ['300 as the number', 'Spring rolls'],
    adaptations: {
      sen:
        'Native to your kitchen and your tone. One tripod, one continuous take during normal prep — the labour is happening anyway, you are only recording it. Fits the 15:00–17:00 window.',
      nonna:
        'Hand-rolling a tray of gnocchi or filling ravioli in one take. Hands only, no face, no dialogue.',
    },
  }),

  P({
    id: 'p14',
    creatorId: 'c10',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p14',
    views: 156000,
    likes: 14200,
    comments: 430,
    ageDays: 16,
    durationS: 15,
    caption: 'restaurant edition 😂 #trend',
    poster: { hue: 320, glyph: '🎵' },
    videoUrl: null,
    attributes: {
      hookType: 'relatability',
      format: 'challenge',
      tone: 'energetic',
      secondaryTone: 'comedy',
      peopleOnCamera: 3,
      chefOnCamera: false,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'trending_sound',
      trendHalfLifeDays: 6,
      propsCostEur: 0,
      staffMinutes: 20,
      cuts: 8,
      avgShotLengthS: 1.9,
    },
    transcript: '[trending audio]',
    timeline: [
      { t: 0, label: 'Audio drop, staff in position' },
      { t: 5, label: 'Beat-matched swaps' },
      { t: 12, label: 'Final pose' },
    ],
    mechanism:
      'Pure trend participation. Performance comes from the audio’s distribution, not the content — which is why it decays to zero within days.',
    essentialElements: ['Being early to the audio'],
    incidentalElements: ['Everything shown on screen'],
    adaptations: {},
  }),

  P({
    id: 'p15',
    creatorId: 'c4',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p15',
    views: 1380000,
    likes: 121000,
    comments: 5400,
    ageDays: 58,
    durationS: 47,
    caption: '€5 version vs €45 version. same four ingredients.',
    poster: { hue: 12, glyph: '⚖️' },
    videoUrl: null,
    attributes: {
      hookType: 'curiosity',
      format: 'before_after',
      tone: 'educational',
      secondaryTone: 'transformation',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'full_kitchen',
      equipment: ['phone', 'tripod', 'light'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 45,
      staffMinutes: 100,
      cuts: 22,
      avgShotLengthS: 2.1,
    },
    transcript: '"Same flour. Same egg. The only difference is forty minutes and knowing when to stop."',
    timeline: [
      { t: 0, label: 'Two plates side by side, prices shown' },
      { t: 6, label: 'Split-screen build begins' },
      { t: 28, label: 'Divergence point named explicitly' },
      { t: 41, label: 'Both finished, tasted' },
    ],
    mechanism:
      'A controlled comparison. Holding the inputs constant makes the skill the only variable, which converts a price objection into an argument for craft.',
    essentialElements: [
      'Genuinely identical inputs',
      'One named divergence point',
      'Both outcomes shown honestly',
    ],
    incidentalElements: ['The specific price gap', 'Split-screen as a technique'],
    adaptations: {
      sen:
        'Run it on pho: instant stock versus your 12-hour broth, same bowl, same noodles. It is the clearest argument for your price point you can make in 45 seconds. Budget the €45 of ingredients and a full 100-minute block.',
    },
  }),

  P({
    id: 'p16',
    creatorId: 'c5',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p16',
    views: 288000,
    likes: 41200,
    comments: 3100,
    ageDays: 42,
    durationS: 36,
    caption: 'he has not had to order in four years.',
    poster: { hue: 190, glyph: '☕' },
    videoUrl: null,
    attributes: {
      hookType: 'relatability',
      format: 'customer_interaction',
      tone: 'heartwarming',
      secondaryTone: 'story',
      peopleOnCamera: 2,
      chefOnCamera: false,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'any_counter',
      spaceRequired: 'counter',
      equipment: ['phone'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 30,
      cuts: 7,
      avgShotLengthS: 5.1,
    },
    transcript: '"Same as always?" — "Same as always." — [it is already being made]',
    timeline: [
      { t: 0, label: 'Regular appears at the door' },
      { t: 3, label: 'Staff start making it before he speaks' },
      { t: 18, label: 'Short exchange, clearly habitual' },
      { t: 30, label: 'He leaves; caption states four years' },
    ],
    mechanism:
      'Evidence of belonging. The viewer is not being told the place is friendly — they watch a relationship that predates the camera.',
    essentialElements: [
      'A real, long-standing regular',
      'The order starting before it is spoken',
      'A duration claim that makes it concrete',
    ],
    incidentalElements: ['Four years specifically', 'The drink itself'],
    adaptations: {
      bosporus:
        'You have regulars in a mall food court, which is the surprising part and therefore the hook. 30 minutes, no props, one phone. Get his written consent first.',
      nonna:
        'Your best-fitting concept overall — the regular table, the order that never changes, the duration claim. Warm, cheap, and exactly your register.',
    },
  }),

  P({
    id: 'p17',
    creatorId: 'c9',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p17',
    views: 98000,
    likes: 8900,
    comments: 260,
    ageDays: 24,
    durationS: 20,
    caption: 'closing time, sped up 🌙',
    poster: { hue: 232, glyph: '🌙' },
    videoUrl: null,
    attributes: {
      hookType: 'relatability',
      format: 'behind_the_scenes',
      tone: 'satisfying',
      secondaryTone: 'craft',
      peopleOnCamera: 2,
      chefOnCamera: false,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'full_kitchen',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 40,
      cuts: 5,
      avgShotLengthS: 4.0,
    },
    transcript: '[no speech]',
    timeline: [
      { t: 0, label: 'Last plate leaves the pass' },
      { t: 5, label: 'Timelapse begins' },
      { t: 15, label: 'Surfaces cleared and wiped' },
      { t: 18, label: 'Lights out' },
    ],
    mechanism:
      'Order restored. The satisfaction is structural — chaos resolving to stillness — and requires no narrative at all.',
    essentialElements: ['A visible start state of disorder', 'Unbroken progression to order', 'A definite end beat'],
    incidentalElements: ['Timelapse speed', 'Closing time specifically'],
    adaptations: {
      sen:
        'One tripod in the corner during your normal close. Zero additional labour — press record on the way past.',
      nonna:
        'Same, and it works around the no-Friday/Saturday rule since you would shoot a quiet weeknight close.',
    },
  }),

  P({
    id: 'p18',
    creatorId: 'c1',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p18',
    views: 356000,
    likes: 28700,
    comments: 1830,
    ageDays: 33,
    durationS: 43,
    caption: 'blind taste test with actual customers 🙈',
    poster: { hue: 62, glyph: '🙈' },
    videoUrl: null,
    attributes: {
      hookType: 'curiosity',
      format: 'customer_reaction',
      tone: 'comedy',
      secondaryTone: 'challenge',
      peopleOnCamera: 4,
      chefOnCamera: true,
      customersOnCamera: true,
      namedPersonDependency: false,
      locationType: 'any_seating',
      spaceRequired: 'shared_seating',
      equipment: ['phone', 'tripod'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 18,
      staffMinutes: 60,
      cuts: 17,
      avgShotLengthS: 2.5,
    },
    transcript: '"Which one is ours?" — "…this one." — "That is the frozen one."',
    timeline: [
      { t: 0, label: 'Two unlabelled samples presented' },
      { t: 8, label: 'First taster commits to an answer' },
      { t: 25, label: 'A taster gets it wrong' },
      { t: 38, label: 'Reveal and reaction' },
    ],
    mechanism:
      'Risking a public loss. The format only works because the business could genuinely come off badly, and the audience knows it.',
    essentialElements: [
      'A real possibility of losing',
      'Tasters with no stake',
      'The result shown regardless of outcome',
    ],
    incidentalElements: ['Two samples specifically', 'The comparison product'],
    adaptations: {
      bosporus:
        'Food-court seating is fine for this — you do not need your own dining room, only a table and two trays. Four on camera stretches your two-person crew, so recruit customers as tasters rather than staff.',
    },
  }),

  P({
    id: 'p19',
    creatorId: 'c4',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p19',
    views: 398000,
    likes: 31000,
    comments: 940,
    ageDays: 66,
    durationS: 33,
    caption: 'three ingredients. one signature dish.',
    poster: { hue: 104, glyph: '🌿' },
    videoUrl: null,
    attributes: {
      hookType: 'authority',
      format: 'food_preparation',
      tone: 'educational',
      secondaryTone: 'craft',
      peopleOnCamera: 1,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'small_kitchen',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 12,
      staffMinutes: 45,
      cuts: 8,
      avgShotLengthS: 4.1,
    },
    transcript: '"Three things. That is it. People do not believe me until they watch."',
    timeline: [
      { t: 0, label: 'Three items placed on the board' },
      { t: 6, label: 'Build begins' },
      { t: 24, label: 'Finished plate' },
    ],
    mechanism: 'Constraint as proof of skill — the shorter the ingredient list, the more the technique carries.',
    essentialElements: ['A hard numeric constraint', 'No hidden additions', 'A finished result worth the claim'],
    incidentalElements: ['Three as the number'],
    adaptations: {},
  }),

  P({
    id: 'p20',
    creatorId: 'c8',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p20',
    views: 690000,
    likes: 71000,
    comments: 4900,
    ageDays: 12,
    durationS: 25,
    caption: 'we told the new guy the fryer was on fire 💀',
    poster: { hue: 0, glyph: '🚨' },
    videoUrl: null,
    attributes: {
      hookType: 'surprise',
      format: 'behind_the_scenes',
      tone: 'comedy',
      secondaryTone: 'shock',
      peopleOnCamera: 3,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'small_kitchen',
      equipment: ['phone'],
      editComplexity: 'heavy_cuts_captions',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 0,
      staffMinutes: 30,
      cuts: 12,
      avgShotLengthS: 2.1,
    },
    transcript: '"FIRE!" — [nothing is on fire]',
    timeline: [
      { t: 0, label: 'Setup whispered to camera' },
      { t: 6, label: 'The shout' },
      { t: 10, label: 'New starter reacts' },
      { t: 20, label: 'Reveal, everyone laughing' },
    ],
    mechanism: 'Staged jeopardy resolved quickly. Works on surprise, which is why it does not survive a second viewing.',
    essentialElements: ['A believable threat', 'A genuine unscripted reaction', 'Fast resolution'],
    incidentalElements: ['The fire premise'],
    adaptations: {},
  }),

  P({
    id: 'p21',
    creatorId: 'c12',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p21',
    views: 445000,
    likes: 52000,
    comments: 2200,
    ageDays: 104,
    durationS: 49,
    caption: 'why this dish is on the menu.',
    poster: { hue: 16, glyph: '📜' },
    videoUrl: null,
    attributes: {
      hookType: 'story',
      format: 'interview',
      tone: 'story',
      secondaryTone: 'heartwarming',
      peopleOnCamera: 2,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_dining_room',
      spaceRequired: 'dining_room',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 20,
      staffMinutes: 70,
      cuts: 10,
      avgShotLengthS: 4.9,
    },
    transcript: '"It was the only thing we could afford to make in the first year."',
    timeline: [
      { t: 0, label: 'Dish placed down' },
      { t: 8, label: 'Story begins' },
      { t: 40, label: 'Return to the plate' },
    ],
    mechanism: 'Origin as justification — the dish stops being an item and becomes evidence.',
    essentialElements: ['A specific hardship', 'A dish still on the menu', 'Told by someone who was there'],
    incidentalElements: ['The first-year framing'],
    adaptations: {},
  }),

  P({
    id: 'p22',
    creatorId: 'c12',
    mediaType: 'reel',
    url: 'https://instagram.com/p/seed-p22',
    views: 512000,
    likes: 63400,
    comments: 3400,
    ageDays: 39,
    durationS: 40,
    caption: 'nonna watched me cook for 40 seconds and this happened',
    poster: { hue: 350, glyph: '👵' },
    videoUrl: null,
    attributes: {
      hookType: 'relatability',
      format: 'behind_the_scenes',
      tone: 'heartwarming',
      secondaryTone: 'comedy',
      peopleOnCamera: 2,
      chefOnCamera: true,
      customersOnCamera: false,
      namedPersonDependency: false,
      locationType: 'any_kitchen',
      spaceRequired: 'full_kitchen',
      equipment: ['phone', 'tripod'],
      editComplexity: 'simple_cuts',
      audioDependency: 'original_dialogue',
      trendHalfLifeDays: null,
      propsCostEur: 10,
      staffMinutes: 55,
      cuts: 9,
      avgShotLengthS: 4.4,
    },
    transcript: '"No." — "What?" — "No." — [she takes the spoon]',
    timeline: [
      { t: 0, label: 'Chef working, unaware' },
      { t: 7, label: 'She enters frame' },
      { t: 14, label: 'Correction, wordless' },
      { t: 33, label: 'He tastes it. She is right.' },
    ],
    mechanism:
      'Authority inversion. The expert being overruled by someone with no title is funny and warm at once, and it argues for the food without a claim.',
    essentialElements: [
      'A real hierarchy to invert',
      'The correction being non-verbal',
      'The professional conceding honestly',
    ],
    incidentalElements: ['The grandmother relationship', 'The specific dish'],
    adaptations: {
      nonna:
        'This is your format and you already have the cast. One tripod, a quiet prep hour, 55 minutes. Chef appears only in profile and barely speaks, which fits his limit — Nonna carries it.',
      sen:
        'Works with any senior family member correcting the kitchen. Keeps your craft register while adding warmth; no guests involved so the consent rule is not in play.',
    },
  }),
];

export const TONE_LABELS = {
  comedy: 'Comedy',
  challenge: 'Challenge',
  satisfying: 'Satisfying',
  craft: 'Craft',
  story: 'Story',
  heartwarming: 'Heartwarming',
  educational: 'Educational',
  transformation: 'Transformation',
  energetic: 'Energetic',
  shock: 'Shock',
  luxury: 'Luxury',
};
